sudo: false
language: python

python: "3.6"

cache:
  - pip
  - apt

# install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv graph

# run tests
script:
  - cd tests
  - python -m pytest -v

# run tests
after_script:
  - pipenv run python-codacy-coverage -r coverage.xml