sudo: false
language: python

python: "3.6"

cache:
  - pip
  - apt

# install dependencies
install:
  - virtualenv -p python3 manifest_service_env
  - source manifest_service_env/bin/activate
  - pip3 install  -r requirements.txt

# run tests
script:
  - cd tests && ls
  - pytest